In [1]:
from bs4 import BeautifulSoup as soup
from urllib.request import urlopen as ureq
from selenium import webdriver
import time
import re

In [2]:
url = "https://ucalgary.ca/pubs/calendar/current/en-4-8.html"

In [3]:
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--ignore-certificate-errors')
chrome_options.add_argument('--incognito')
chrome_options.add_argument('--headless')

driver = webdriver.Chrome("C:\\Users\\jerry\\Downloads\\chromedriver", options=chrome_options)

In [4]:
driver.get(url)
time.sleep(3)

# 1. Collect Course links for driver to click on

In [5]:
page_soup = soup(driver.page_source, 'lxml')

In [6]:
core_container = page_soup.find("span", {"id": "ctl00_ctl00_pageContent_ctl01_ctl02_cnBody"})
core_container

<span class="generic-body" id="ctl00_ctl00_pageContent_ctl01_ctl02_cnBody">
<ul>
<li>
<a class="link-text" href="en-4-1.html">First Year Curriculum</a>
</li>
<li><a class="link-text" href="chemistry.html#43028">Chemistry 379</a>
</li>
<li><a class="link-text" href="digital-engineering.html#47170">Digital Engineering 319</a>, <a class="link-text" href="digital-engineering.html#47171">407</a>
</li>
<li><a class="link-text" href="engineering.html#10165">Engineering 311</a>, <a class="link-text" href="engineering.html#10169">349</a>
</li>
<li><a class="link-text" href="manufacturing-engineering.html#7929">Manufacturing Engineering 417</a>
</li>
<li><a class="link-text" href="mechanical-engineering.html#7870">Mechanical Engineering 101</a>, <a class="link-text" href="mechanical-engineering.html#42366">317</a>, <a class="link-text" href="mechanical-engineering.html#7871">337</a>, <a class="link-text" href="mechanical-engineering.html#32039">339</a>, <a class="link-text" href="mechanical-engi

In [7]:
technical_elective_container = page_soup.find("span", {"id": "ctl00_ctl00_pageContent_ctl10_ctl02_cnBody"})
technical_elective_container

<span class="generic-body" id="ctl00_ctl00_pageContent_ctl10_ctl02_cnBody">
<p>Students completing the Regular Program may request a maximum of one (1) technical elective substitution from the Associate Head (Undergraduate Studies). NOTE: Not all technical electives may be offered every year.</p>
<ul>
<li><a class="link-text" href="biomedical-engineering.html#9933">Biomedical Engineering 509</a>, <a class="link-text" href="biomedical-engineering.html#9936">515</a>, <a class="link-text" href="biomedical-engineering.html#42189">523</a>, <a class="link-text" href="biomedical-engineering.html#39336">525</a>
</li>
<li><a class="link-text" href="energy-and-environment-engineering.html#7609">Energy and Environment, Engineering 575</a>
</li>
<li><a class="link-text" href="engineering.html#40440">Engineering 515</a>
</li>
<li><a class="link-text" href="mechanical-engineering.html#39333">Mechanical Engineering 505</a>, <a class="link-text" href="mechanical-engineering.html#7881">519</a>, <a clas

In [8]:
link_texts = core_container.findAll("a", {"class": "link-text"}) + technical_elective_container.findAll("a", {"class": "link-text"})
link_texts = [link_text.text for link_text in link_texts]
link_texts

['First Year Curriculum',
 'Chemistry 379',
 'Digital Engineering 319',
 '407',
 'Engineering 311',
 '349',
 'Manufacturing Engineering 417',
 'Mechanical Engineering 101',
 '317',
 '337',
 '339',
 '341',
 '421',
 '461',
 '471',
 '473',
 '479',
 '485',
 '493',
 '495',
 '585',
 '599',
 'Engineering 501',
 '502',
 'Engineering 503',
 '504',
 'Mechanical Engineering 501',
 '502',
 'Mathematics 375',
 'Physics 365',
 '369',
 'Mechanical Engineering Technical Electives',
 'Complementary Studies ',
 'Biomedical Engineering 509',
 '515',
 '523',
 '525',
 'Energy and Environment, Engineering 575',
 'Engineering 515',
 'Mechanical Engineering 505',
 '519',
 '521',
 '547',
 '561',
 '570',
 '571',
 '572',
 '573',
 '574',
 '583',
 '587',
 '595',
 '597',
 'Manufacturing Engineering 501',
 '503',
 '509',
 '514',
 '517',
 '527',
 '533',
 'Petroleum Engineering 521',
 '555',
 '561',
 '563']

In [9]:
link_texts = [link_text for link_text in link_texts if bool(re.match("[A-Za-z, ]*[0-9]{3}", link_text))]
link_texts

['Chemistry 379',
 'Digital Engineering 319',
 '407',
 'Engineering 311',
 '349',
 'Manufacturing Engineering 417',
 'Mechanical Engineering 101',
 '317',
 '337',
 '339',
 '341',
 '421',
 '461',
 '471',
 '473',
 '479',
 '485',
 '493',
 '495',
 '585',
 '599',
 'Engineering 501',
 '502',
 'Engineering 503',
 '504',
 'Mechanical Engineering 501',
 '502',
 'Mathematics 375',
 'Physics 365',
 '369',
 'Biomedical Engineering 509',
 '515',
 '523',
 '525',
 'Energy and Environment, Engineering 575',
 'Engineering 515',
 'Mechanical Engineering 505',
 '519',
 '521',
 '547',
 '561',
 '570',
 '571',
 '572',
 '573',
 '574',
 '583',
 '587',
 '595',
 '597',
 'Manufacturing Engineering 501',
 '503',
 '509',
 '514',
 '517',
 '527',
 '533',
 'Petroleum Engineering 521',
 '555',
 '561',
 '563']

problem: many link texts are identical but point to different courses

In [20]:
driver.get("https://ucalgary.ca/pubs/calendar/current/en-4-8.html")
links = driver.find_elements_by_link_text("502")
for i in range(len(links)):
    link = driver.find_elements_by_link_text("502")[i]
    link.click()
    time.sleep(3)
    print(driver.current_url)
    driver.get("https://ucalgary.ca/pubs/calendar/current/en-4-8.html")
    time.sleep(3)

https://ucalgary.ca/pubs/calendar/current/engineering.html#39790
https://ucalgary.ca/pubs/calendar/current/mechanical-engineering.html#43922
https://ucalgary.ca/pubs/calendar/current/engineering.html#39790
https://ucalgary.ca/pubs/calendar/current/mechanical-engineering.html#43922
https://ucalgary.ca/pubs/calendar/current/mechanical-engineering.html#43922
https://ucalgary.ca/pubs/calendar/current/engineering.html#39790


# 2. Automation script to scrape all courses

In [21]:
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import StaleElementReferenceException

course_codes = []
course_names = []
course_descs = []
counter = 0

visited_ids = [] #to keep track of which link has been clicked and avoid clicking on links with the same course code
#ex. multiple links in the page has text "502" - mech 502 and eng 502

driver.get("https://ucalgary.ca/pubs/calendar/current/en-4-8.html")
    
for link_text in link_texts:
    #go to course page
    try:
        links = driver.find_elements_by_link_text(link_text)
    except NoSuchElementException:
        print("no link for {}".format(link_text))
        continue
    time.sleep(2)
    
    for i in range(len(links)):
        
        link = driver.find_elements_by_link_text(link_text)[i]
        link.click()
        time.sleep(2)
    
        #scrape course info
        page_soup = soup(driver.page_source, 'lxml')
        #get the id of the table containing the specific course information
        starting_index = driver.current_url.index("#")+1
        table_id = driver.current_url[starting_index:]
        
        #check if table id has already been visited
        if table_id in visited_ids:
            driver.get("https://ucalgary.ca/pubs/calendar/current/en-4-8.html")
            time.sleep(2)
            continue
        
        visited_ids.append(table_id)
        
        #locate the container/table using the id
        container = page_soup.find("a", {"name": table_id})
        container = container.parent
        
        course_info = container.findAll("span", {"class": "course-code"})
        course_codes.append(course_info[0].text.strip() + " " + course_info[1].text.strip())
        course_names.append(course_info[2].text.strip())
        course_descs.append(container.find("span", {"class": "course-desc"}).text)
        
        print("Scraped ", course_codes[-1])
        counter += 1
        
        #go to course list page
        driver.get("https://ucalgary.ca/pubs/calendar/current/en-4-8.html")
        time.sleep(2)
        
print("Finished scraping {} courses".format(counter))

Scraped  Chemistry 379
Scraped  Digital Engineering 319
Scraped  Digital Engineering 407
Scraped  Engineering 311
Scraped  Engineering 349
Scraped  Manufacturing Engineering 417
Scraped  Mechanical Engineering 101
Scraped  Mechanical Engineering 317
Scraped  Mechanical Engineering 337
Scraped  Mechanical Engineering 339
Scraped  Mechanical Engineering 341
Scraped  Mechanical Engineering 421
Scraped  Mechanical Engineering 461
Scraped  Mechanical Engineering 471
Scraped  Mechanical Engineering 473
Scraped  Mechanical Engineering 479
Scraped  Mechanical Engineering 485
Scraped  Mechanical Engineering 493
Scraped  Mechanical Engineering 495
Scraped  Mechanical Engineering 585
Scraped  Mechanical Engineering 599
Scraped  Engineering 501
Scraped  Engineering 502
Scraped  Mechanical Engineering 502
Scraped  Engineering 503
Scraped  Engineering 504
Scraped  Mechanical Engineering 501
Scraped  Mathematics 375
Scraped  Physics 365
Scraped  Physics 369
Scraped  Biomedical Engineering 509
Scraped

NOTE: NEED TO REMOVE Electrical eng 525 AND Petroleum eng 533, NOT REGULAR MECH ENG PROGRAM COURSES. THEY GET SCRAPED DUE TO POOR FORMATTING ON UCALG SITE AND DUPLICATE COURSE CODE LINKS (EX. MULTIPLE 525 LINKS

In [23]:
print(len(link_texts))
print(len(course_codes))

61
63


In [24]:
false_courses = ["Electrical Engineering 525", "Petroleum Engineering 533"]
course_codes_final = []
course_names_final = []
course_descs_final = []

for i in range(len(course_codes)):
    if course_codes[i] not in false_courses:
        course_codes_final.append(course_codes[i])
        course_names_final.append(course_names[i])
        course_descs_final.append(course_descs[i])

In [28]:
len(course_descs_final)

61

# 3. also need to scrape engineering-targeted CSEs

In [29]:
cse_url = "https://ucalgary.ca/pubs/calendar/current/en-3-3.html#3253"
uClient = ureq(cse_url)
page_html = uClient.read()
uClient.close()
cse_page_soup = soup(page_html, "html.parser")

cse_container = cse_page_soup.find("span", {"id": "ctl00_ctl00_pageContent_ctl05_ctl02_cnBody"})
cse_container

<span class="generic-body" id="ctl00_ctl00_pageContent_ctl05_ctl02_cnBody">
<p>The following six complementary studies courses are required for all students<sup>1,2</sup> in the School: </p>
<p>(a) <a class="link-text" href="engineering.html#10161">Engineering 209</a> (<a class="link-text" href="economics.html#9978">Economics 209</a>)<sup>3 </sup>- not open to first-year students </p>
<p>(b) <a class="link-text" href="engineering.html#10173">Engineering 481</a></p>
<p>(c) <a class="link-text" href="engineering.html#43070">Engineering 213</a> <sup></sup>or <a class="link-text" href="communication-media-studies.html#7287">Communications Studies 363</a></p>
<p>(d) <a class="link-text" href="engineering.html#10174">Engineering 513</a></p>
<p>(e) Two general complementary studies courses (see below) are required for all programs except in the following cases:</p>
<ul>
<li>For the Chemical Engineering Programs, students are required to take three general complementary studies courses<sup>3</

In [30]:
cse_link_texts = cse_container.findAll("a", {"class": "link-text"})
cse_link_texts = [link_text.text for link_text in cse_link_texts]
cse_link_texts = list(dict.fromkeys(cse_link_texts))
cse_link_texts

['Engineering 209',
 'Economics 209',
 'Engineering 481',
 'Engineering 213',
 'Communications Studies 363',
 'Engineering 513',
 'Energy Management 301',
 'Strategy and Global Management 395',
 'Geomatics Engineering 587',
 '\n4.6. Energy Engineering\n',
 'Economics 201',
 'Economics 203',
 'Strategy and Global Management 217']

In [31]:
#only the first 6 cse's are engineering-related and relevant to the mechanical engineering program
cse_link_texts = cse_link_texts[:6]
cse_link_texts

['Engineering 209',
 'Economics 209',
 'Engineering 481',
 'Engineering 213',
 'Communications Studies 363',
 'Engineering 513']

In [32]:
counter = 0

driver.get("https://ucalgary.ca/pubs/calendar/current/en-3-3.html#3253")
    
for link_text in cse_link_texts:
    #go to course page
    try:
        link = driver.find_element_by_link_text(link_text)
    except NoSuchElementException:
        print("no link for {}".format(link_text))
        continue

    time.sleep(2)
    link.click()    
    time.sleep(2)
    
    #scrape course info
    page_soup = soup(driver.page_source, 'lxml')
    #get the id of the table containing the specific course information
    starting_index = driver.current_url.index("#")+1
    table_id = driver.current_url[starting_index:]
    
    #locate the container/table using the id
    container = page_soup.find("a", {"name": table_id})
    container = container.parent
    
    course_info = container.findAll("span", {"class": "course-code"})
    course_codes_final.append(course_info[0].text.strip() + " " + course_info[1].text.strip())
    course_names_final.append(course_info[2].text.strip())
    course_descs_final.append(container.find("span", {"class": "course-desc"}).text)
    
    print("Scraped ", course_codes_final[-1])
    counter += 1
    
    #go to course list page
    driver.back()
    time.sleep(2)
        
print("Finished scraping {} courses".format(counter))

Scraped  Engineering 209
Scraped  Economics 209
Scraped  Engineering 481
Scraped  Engineering 213
Scraped  Communication and Media Studies 363
Scraped  Engineering 513
Finished scraping 6 courses


In [33]:
len(course_codes_final)

67

# 4. Write to CSV

In [34]:
import pandas as pd

df = pd.DataFrame({
    "Course Number": course_codes_final,
    "Course Name": course_names_final,
    "Course Description": course_descs_final
})

df

Course Number  \
0                         Chemistry 379   
1               Digital Engineering 319   
2               Digital Engineering 407   
3                       Engineering 311   
4                       Engineering 349   
..                                  ...   
62                        Economics 209   
63                      Engineering 481   
64                      Engineering 213   
65  Communication and Media Studies 363   
66                      Engineering 513   

                                          Course Name  \
0                   Materials Chemistry for Engineers   
1        Probability, Statistics and Machine Learning   
2                     Computational Numerical Methods   
3                          Engineering Thermodynamics   
4                                            Dynamics   
..                                                ...   
62                              Engineering Economics   
63                             Technology and Society   
64                          Engineering Communication   
65           Professional and Technical Communication   
66  The Role and Responsibilities of the Professio...   

                                   Course Description  
0   An introduction to materials chemistry with in...  
1   Presentation and description of data, introduc...  
2   Numerical computational procedures to solve en...  
3   Energy, thermodynamic systems, properties and ...  
4   Kinematics of particles and rigid bodies: rect...  
..                                                ...  
62  The basic tools and methodology of engineering...  
63  An interpretive course on the interrelationshi...  
64  Professional and technical communication with ...  
65  An introduction to professional and technical ...  
66  The professional duties and responsibilities o...  

[67 rows x 3 columns]

In [35]:
df.to_csv('UCalgary_MechEng_Core_and_Elective_Courses.csv', index = False)

In [ ]:
driver.quit()